# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '0001_initial'),
        ('account', '0002_auto_20171023_2203'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrecord',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Transaction'),
        ),
        migrations.AddField(
            model_name='bookingrecord',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Tutor'),
        ),
    ]
