# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='sessions',
            field=models.ManyToManyField(to='scheduler.Session'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tags',
            field=models.ManyToManyField(to='account.SubjectTag'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
    ]
